In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/raw/healthcare_disease_risk.csv")

df.head()

,Age,Gender,BMI,BloodPressure,Cholesterol,Glucose,Smoking,PhysicalActivity,FamilyHistory,HeartRate,Disease_Risk
0,56,Male,39.3,96,164,111,No,Medium,No,78,0
1,69,Male,22.0,157,177,137,Yes,Medium,Yes,64,1
2,46,Male,18.5,108,298,139,Yes,Medium,Yes,67,1
3,32,Female,33.8,120,245,147,Yes,Medium,No,98,1
4,60,Female,27.2,124,281,159,No,Medium,Yes,93,1

In [3]:
print("Dataset Shape:", df.shape)

Dataset Shape: (2000, 11)

In [4]:
X = df.drop("Disease_Risk", axis=1)
y = df["Disease_Risk"]

In [5]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2000, 10)
y shape: (2000,)

In [6]:
categorical_columns = X.select_dtypes(include="object").columns

print("Categorical columns:")
print(categorical_columns.tolist())

Categorical columns:
['Gender', 'Smoking', 'PhysicalActivity', 'FamilyHistory']

In [7]:
X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

In [8]:
print(X.head())

   Age   BMI  BloodPressure  Cholesterol  Glucose  HeartRate  Gender_Male  \
0   56  39.3             96          164      111         78         True
1   69  22.0            157          177      137         64         True
2   46  18.5            108          298      139         67         True
3   32  33.8            120          245      147         98        False
4   60  27.2            124          281      159         93        False

   Smoking_Yes  PhysicalActivity_Low  PhysicalActivity_Medium  \
0        False                 False                     True
1         True                 False                     True
2         True                 False                     True
3         True                 False                     True
4        False                 False                     True

   FamilyHistory_Yes
0              False
1               True
2               True
3              False
4               True

In [9]:
print("Number of features:", X.shape[1])

Number of features: 11

In [10]:
print(y.value_counts())

Disease_Risk
1    1464
0     536
Name: count, dtype: int64

In [11]:
print(y.value_counts(normalize=True) * 100)

Disease_Risk
1    73.2
0    26.8
Name: proportion, dtype: float64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [13]:
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (1600, 11)
Testing data: (400, 11)

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
scaler.fit_transform(X_train)

array([[-1.43387461, -0.4311565 ,  1.00020059, ..., -0.69883624,
         1.36464429, -1.00375706],
       [ 0.06920426, -1.19202091, -1.18917858, ..., -0.69883624,
         1.36464429, -1.00375706],
       [ 0.73723931,  1.39174782,  0.73132946, ..., -0.69883624,
         1.36464429,  0.996257  ],
       ...,
       [-0.43182203,  0.45651865,  0.76973962, ..., -0.69883624,
        -0.7327917 ,  0.996257  ],
       [-0.37615244, -0.87499407, -1.0739481 , ..., -0.69883624,
         1.36464429,  0.996257  ],
       [-1.04418749,  1.62951795,  0.57768882, ..., -0.69883624,
         1.36464429, -1.00375706]], shape=(1600, 11))

In [16]:
scaler.transform(X_test)

array([[-1.04418749, -1.17616957, -0.99712778, ..., -0.69883624,
        -0.7327917 ,  0.996257  ],
       [ 0.57023054,  0.13949181, -1.38122939, ..., -0.69883624,
         1.36464429,  0.996257  ],
       [ 0.12487384,  1.31249111,  0.30881769, ..., -0.69883624,
         1.36464429,  0.996257  ],
       ...,
       [ 0.45889137, -0.98595347, -1.49645987, ..., -0.69883624,
         1.36464429,  0.996257  ],
       [-1.37820502, -0.4311565 , -0.92030745, ..., -0.69883624,
         1.36464429, -1.00375706],
       [ 1.68362229, -0.20923771,  1.19225139, ..., -0.69883624,
         1.36464429,  0.996257  ]], shape=(400, 11))

In [17]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

In [18]:
X_train_scaled.head()

,Age,BMI,BloodPressure,Cholesterol,Glucose,HeartRate,Gender_Male,Smoking_Yes,PhysicalActivity_Low,PhysicalActivity_Medium,FamilyHistory_Yes
1312,-1.433875,-0.431157,1.000201,0.033927,1.259350,-1.024422,-0.969223,1.034339,-0.698836,1.364644,-1.003757
159,0.069204,-1.192021,-1.189179,-0.395038,-0.308130,-0.342785,1.031754,1.034339,-0.698836,1.364644,-1.003757
1839,0.737239,1.391748,0.731329,-1.096982,1.048793,-0.500086,1.031754,-0.966801,-0.698836,1.364644,0.996257
58,-0.598831,-1.128616,-1.688511,-0.239051,-1.290729,-1.181723,1.031754,1.034339,-0.698836,1.364644,0.996257
1299,-0.042135,-0.573819,0.001536,0.072924,1.703860,1.020489,1.031754,-0.966801,1.430950,-0.732792,0.996257

In [19]:
train_data = X_train_scaled.copy()
train_data["Disease_Risk"] = y_train

test_data = X_test_scaled.copy()
test_data["Disease_Risk"] = y_test

train_data.to_csv(
    "../data/processed/train_data.csv",
    index=False
)

test_data.to_csv(
    "../data/processed/test_data.csv",
    index=False
)

print("Training and testing datasets saved successfully!")

Training and testing datasets saved successfully!