In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
model = joblib.load(
    "../models/healthcare_disease_risk_model.pkl"
)

print("Model loaded successfully!")

Model loaded successfully!

In [3]:
scaler = joblib.load(
    "../models/healthcare_scaler.pkl"
)

print("Scaler loaded successfully!")

Scaler loaded successfully!

In [5]:
import pandas as pd
import joblib
import os

train_data = pd.read_csv(
    "../data/processed/train_data.csv"
)

feature_names = train_data.drop(
    "Disease_Risk",
    axis=1
).columns.tolist()

os.makedirs("../models", exist_ok=True)

joblib.dump(
    feature_names,
    "../models/feature_names.pkl"
)

print("feature_names.pkl created successfully!")

feature_names.pkl created successfully!

In [7]:
feature_names = joblib.load(
    "../models/feature_names.pkl"
)

print("Feature names loaded successfully!")

Feature names loaded successfully!

In [8]:
patient = {
    "Age": 45,
    "BMI": 27.5,
    "BloodPressure": 130,
    "Cholesterol": 210,
    "Glucose": 115,
    "HeartRate": 78,
    "Gender": "Male",
    "Smoking": "No",
    "PhysicalActivity": "Medium",
    "FamilyHistory": "Yes"
}

print(patient)

{'Age': 45, 'BMI': 27.5, 'BloodPressure': 130, 'Cholesterol': 210, 'Glucose': 115, 'HeartRate': 78, 'Gender': 'Male', 'Smoking': 'No', 'PhysicalActivity': 'Medium', 'FamilyHistory': 'Yes'}

In [9]:
patient_df = pd.DataFrame([patient])

patient_df

,Age,BMI,BloodPressure,Cholesterol,Glucose,HeartRate,Gender,Smoking,PhysicalActivity,FamilyHistory
0,45,27.5,130,210,115,78,Male,No,Medium,Yes

In [10]:
patient_encoded = pd.get_dummies(
    patient_df,
    columns=[
        "Gender",
        "Smoking",
        "PhysicalActivity",
        "FamilyHistory"
    ],
    drop_first=True
)

patient_encoded

   Age   BMI  BloodPressure  Cholesterol  Glucose  HeartRate
0   45  27.5            130          210      115         78

In [11]:
patient_encoded = patient_encoded.reindex(
    columns=feature_names,
    fill_value=0
)

print("Patient features:", patient_encoded.shape)
print(patient_encoded)

Patient features: (1, 11)
   Age   BMI  BloodPressure  Cholesterol  Glucose  HeartRate  Gender_Male  \
0   45  27.5            130          210      115         78            0

   Smoking_Yes  PhysicalActivity_Low  PhysicalActivity_Medium  \
0            0                     0                        0

   FamilyHistory_Yes
0                  0

In [12]:
patient_scaled = scaler.transform(
    patient_encoded
)

print("Patient data scaled successfully!")

Patient data scaled successfully!

In [13]:
prediction = model.predict(
    patient_scaled
)

print("Prediction:", prediction[0])

Prediction: 0

In [14]:
if prediction[0] == 1:
    risk = "High Risk"
else:
    risk = "Low Risk"

print("Disease Risk:", risk)

Disease Risk: Low Risk

In [15]:
probability = model.predict_proba(
    patient_scaled
)[0][1]

print(
    "Risk Probability:",
    round(probability * 100, 2),
    "%"
)

Risk Probability: 0.0 %

In [16]:
def predict_disease_risk(patient):

    patient_df = pd.DataFrame([patient])

    patient_encoded = pd.get_dummies(
        patient_df,
        columns=[
            "Gender",
            "Smoking",
            "PhysicalActivity",
            "FamilyHistory"
        ],
        drop_first=True
    )

    patient_encoded = patient_encoded.reindex(
        columns=feature_names,
        fill_value=0
    )

    patient_scaled = scaler.transform(
        patient_encoded
    )

    prediction = model.predict(
        patient_scaled
    )[0]

    probability = model.predict_proba(
        patient_scaled
    )[0][1]

    if prediction == 1:
        risk = "High Risk"
    else:
        risk = "Low Risk"

    return risk, probability

In [17]:
risk, probability = predict_disease_risk(patient)

print("================================")
print("     DISEASE RISK RESULT")
print("================================")
print("Risk:", risk)
print("Probability:", round(probability * 100, 2), "%")

================================
     DISEASE RISK RESULT
================================
Risk: Low Risk
Probability: 0.0 %

In [1]:
!pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.9-py3-none-any.whl (140 kB)
     ---------------------------------------- 0.0/140.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/140.1 kB ? eta -:--:--
     ----------- --------------------------- 41.0/140.1 kB 1.9 MB/s eta 0:00:01
     ---------------- -------------------- 61.4/140.1 kB 648.1 kB/s eta 0:00:01
     ---------------- -------------------- 61.4/140.1 kB 648.1 kB/s eta 0:00:01
     ---------------- -------------------- 61.4/140.1 kB 648.1 kB/s eta 0:00:01
     ------------------ ------------------ 71.7/140.1 kB 280.5 kB/s eta 0:00:01
     ------------------ ------------------ 71.7/140.1 kB 280.5 kB/s eta 0:00:01
     ------------------------ ------------ 92.2/140.1 kB 275.8 kB/s eta 0:00:01
     ------------------------ ------------ 92.2/140.1 kB 275.8 kB/s eta 0:00:01
     ------------------------ ------------ 92.2/140.1 kB 275.8 kB/s eta 0:00:01
     ------------------------ ------------ 92.2/140.1 kB 275.8 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     -------------------------- --------- 102.4/140.1 kB 173.2 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------- ---- 122.9/140.1 kB 131.0 kB/s eta 0:00:01
     ------------------------------------- 140.1/140.1 kB 95.5 kB/s eta 0:00:00
Requirement already satisfied: ipython>=6.1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (8.39.0)
Collecting jupyterlab_widgets~=3.0.17
  Downloading jupyterlab_widgets-3.0.17-py3-none-any.whl (217 kB)
     ---------------------------------------- 0.0/217.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/217.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/217.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/217.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/217.3 kB ? eta -:--:--
     - -------------------------------------- 10.2/217.3 kB ? eta -:--:--
     - -------------------------------------- 10.2/217.3 kB ? eta -:--:--
     - -------------------------------------- 10.2/217.3 kB ? eta -:--:--
     ----- ------------------------------- 30.7/217.3 kB 130.4 kB/s eta 0:00:02
     ----- ------------------------------- 30.7/217.3 kB 130.4 kB/s eta 0:00:02
     ----- ------------------------------- 30.7/217.3 kB 130.4 kB/s eta 0:00:02
     ----- ------------------------------- 30.7/217.3 kB 130.4 kB/s eta 0:00:02
     ----- ------------------------------- 30.7/217.3 kB 130.4 kB/s eta 0:00:02
     ------- ------------------------------ 41.0/217.3 kB 85.3 kB/s eta 0:00:03
     ------- ------------------------------ 41.0/217.3 kB 85.3 kB/s eta 0:00:03
     ------- ------------------------------ 41.0/217.3 kB 85.3 kB/s eta 0:00:03
     ---------- --------------------------- 61.4/217.3 kB 99.2 kB/s eta 0:00:02
     ---------- --------------------------- 61.4/217.3 kB 99.2 kB/s eta 0:00:02
     ---------- --------------------------- 61.4/217.3 kB 99.2 kB/s eta 0:00:02
     ------------ ------------------------- 71.7/217.3 kB 95.8 kB/s eta 0:00:02
     ------------ ------------------------- 71.7/217.3 kB 95.8 kB/s eta 0:00:02
     ------------ ------------------------- 71.7/217.3 kB 95.8 kB/s eta 0:00:02
     -------------- ----------------------- 81.9/217.3 kB 86.6 kB/s eta 0:00:02
     ---------------- --------------------- 92.2/217.3 kB 98.9 kB/s eta 0:00:02
     ---------------- --------------------- 92.2/217.3 kB 98.9 kB/s eta 0:00:02
     ------------------ ----------------- 112.6/217.3 kB 104.0 kB/s eta 0:00:02
     ------------------ ----------------- 112.6/217.3 kB 104.0 kB/s eta 0:00:02
     ------------------ ----------------- 112.6/217.3 kB 104.0 kB/s eta 0:00:02
     ------------------ ----------------- 112.6/217.3 kB 104.0 kB/s eta 0:00:02
     -------------------- ---------------- 122.9/217.3 kB 94.8 kB/s eta 0:00:01
     -------------------- ---------------- 122.9/217.3 kB 94.8 kB/s eta 0:00:01
     -------------------- ---------------- 122.9/217.3 kB 94.8 kB/s eta 0:00:01
     ------------------------ ------------ 143.4/217.3 kB 99.0 kB/s eta 0:00:01
     ------------------------ ------------ 143.4/217.3 kB 99.0 kB/s eta 0:00:01
     ------------------------ ------------ 143.4/217.3 kB 99.0 kB/s eta 0:00:01
     ------------------------ ------------ 143.4/217.3 kB 99.0 kB/s eta 0:00:01
     ------------------------ ------------ 143.4/217.3 kB 99.0 kB/s eta 0:00:01
     -------------------------- ---------- 153.6/217.3 kB 89.9 kB/s eta 0:00:01
     -------------------------- ---------- 153.6/217.3 kB 89.9 kB/s eta 0:00:01
     -------------------------- ---------- 153.6/217.3 kB 89.9 kB/s eta 0:00:01
     -------------------------- ---------- 153.6/217.3 kB 89.9 kB/s eta 0:00:01
     -------------------------- ---------- 153.6/217.3 kB 89.9 kB/s eta 0:00:01
     ----------------------------- ------- 174.1/217.3 kB 88.8 kB/s eta 0:00:01
     ----------------------------- ------- 174.1/217.3 kB 88.8 kB/s eta 0:00:01
     ----------------------------- ------- 174.1/217.3 kB 88.8 kB/s eta 0:00:01
     ----------------------------- ------- 174.1/217.3 kB 88.8 kB/s eta 0:00:01
     --------------------------------- --- 194.6/217.3 kB 89.3 kB/s eta 0:00:01
     --------------------------------- --- 194.6/217.3 kB 89.3 kB/s eta 0:00:01
     --------------------------------- --- 194.6/217.3 kB 89.3 kB/s eta 0:00:01
     ---------------------------------- -- 204.8/217.3 kB 89.6 kB/s eta 0:00:01
     ------------------------------------- 217.3/217.3 kB 92.6 kB/s eta 0:00:00
Requirement already satisfied: traitlets>=4.3.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (5.15.1)
Collecting widgetsnbextension~=4.0.16
  Downloading widgetsnbextension-4.0.16-py3-none-any.whl (2.2 MB)
     ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
     ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
      --------------------------------------- 0.0/2.2 MB 217.9 kB/s eta 0:00:11
      --------------------------------------- 0.0/2.2 MB 217.9 kB/s eta 0:00:11
      --------------------------------------- 0.0/2.2 MB 217.9 kB/s eta 0:00:11
     - -------------------------------------- 0.1/2.2 MB 233.8 kB/s eta 0:00:10
     - -------------------------------------- 0.1/2.2 MB 231.0 kB/s eta 0:00:10
     - -------------------------------------- 0.1/2.2 MB 249.8 kB/s eta 0:00:09
     - -------------------------------------- 0.1/2.2 MB 245.8 kB/s eta 0:00:09
     -- ------------------------------------- 0.1/2.2 MB 277.4 kB/s eta 0:00:08
     -- ------------------------------------- 0.1/2.2 MB 293.9 kB/s eta 0:00:08
     -- ------------------------------------- 0.2/2.2 MB 286.7 kB/s eta 0:00:08
     --- ------------------------------------ 0.2/2.2 MB 301.2 kB/s eta 0:00:07
     --- ------------------------------------ 0.2/2.2 MB 311.3 kB/s eta 0:00:07
     --- ------------------------------------ 0.2/2.2 MB 311.3 kB/s eta 0:00:07
     ---- ----------------------------------- 0.2/2.2 MB 313.3 kB/s eta 0:00:07
     ---- ----------------------------------- 0.2/2.2 MB 313.3 kB/s eta 0:00:07
     ---- ----------------------------------- 0.3/2.2 MB 308.4 kB/s eta 0:00:07
     ---- ----------------------------------- 0.3/2.2 MB 303.3 kB/s eta 0:00:07
     ----- ---------------------------------- 0.3/2.2 MB 316.0 kB/s eta 0:00:07
     ----- ---------------------------------- 0.3/2.2 MB 317.0 kB/s eta 0:00:07
     ------ --------------------------------- 0.3/2.2 MB 327.7 kB/s eta 0:00:06
     ------ --------------------------------- 0.3/2.2 MB 318.2 kB/s eta 0:00:06
     ------ --------------------------------- 0.4/2.2 MB 332.5 kB/s eta 0:00:06
     ------ --------------------------------- 0.4/2.2 MB 332.1 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.2 MB 340.5 kB/s eta 0:00:06
     ------- -------------------------------- 0.4/2.2 MB 340.2 kB/s eta 0:00:06
     -------- ------------------------------- 0.5/2.2 MB 351.2 kB/s eta 0:00:05
     -------- ------------------------------- 0.5/2.2 MB 342.6 kB/s eta 0:00:06
     --------- ------------------------------ 0.5/2.2 MB 349.6 kB/s eta 0:00:05
     --------- ------------------------------ 0.5/2.2 MB 359.4 kB/s eta 0:00:05
     --------- ------------------------------ 0.6/2.2 MB 365.7 kB/s eta 0:00:05
     ---------- ----------------------------- 0.6/2.2 MB 370.7 kB/s eta 0:00:05
     ---------- ----------------------------- 0.6/2.2 MB 366.2 kB/s eta 0:00:05
     ----------- ---------------------------- 0.6/2.2 MB 380.6 kB/s eta 0:00:05
     ----------- ---------------------------- 0.6/2.2 MB 379.7 kB/s eta 0:00:05
     ------------ --------------------------- 0.7/2.2 MB 383.9 kB/s eta 0:00:05
     ------------ --------------------------- 0.7/2.2 MB 383.9 kB/s eta 0:00:05
     ------------ --------------------------- 0.7/2.2 MB 383.9 kB/s eta 0:00:05
     ------------ --------------------------- 0.7/2.2 MB 383.9 kB/s eta 0:00:05
     ------------- -------------------------- 0.7/2.2 MB 383.6 kB/s eta 0:00:04
     ------------- -------------------------- 0.8/2.2 MB 376.8 kB/s eta 0:00:04
     ------------- -------------------------- 0.8/2.2 MB 375.2 kB/s eta 0:00:04
     ------------- -------------------------- 0.8/2.2 MB 375.2 kB/s eta 0:00:04
     ------------- -------------------------- 0.8/2.2 MB 375.2 kB/s eta 0:00:04
     -------------- ------------------------- 0.8/2.2 MB 359.9 kB/s eta 0:00:04
     -------------- ------------------------- 0.8/2.2 MB 359.9 kB/s eta 0:00:04
     -------------- ------------------------- 0.8/2.2 MB 359.1 kB/s eta 0:00:04
     -------------- ------------------------- 0.8/2.2 MB 359.1 kB/s eta 0:00:04
     --------------- ------------------------ 0.8/2.2 MB 346.9 kB/s eta 0:00:04
     --------------- ------------------------ 0.8/2.2 MB 346.9 kB/s eta 0:00:04
     --------------- ------------------------ 0.9/2.2 MB 344.2 kB/s eta 0:00:04
     --------------- ------------------------ 0.9/2.2 MB 344.2 kB/s eta 0:00:04
     --------------- ------------------------ 0.9/2.2 MB 335.5 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 333.4 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 333.4 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 325.8 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 325.8 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 325.8 kB/s eta 0:00:05
     ---------------- ----------------------- 0.9/2.2 MB 325.9 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 324.2 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 324.2 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 319.2 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 319.2 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 317.7 kB/s eta 0:00:04
     ----------------- ---------------------- 1.0/2.2 MB 317.7 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 310.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 310.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 307.5 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 307.5 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 299.5 kB/s eta 0:00:04
     ------------------ --------------------- 1.0/2.2 MB 299.5 kB/s eta 0:00:04
     ------------------ --------------------- 1.1/2.2 MB 297.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.1/2.2 MB 297.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.1/2.2 MB 297.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.1/2.2 MB 297.1 kB/s eta 0:00:04
     ------------------ --------------------- 1.1/2.2 MB 297.1 kB/s eta 0:00:04
     ------------------- -------------------- 1.1/2.2 MB 282.8 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 282.8 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 282.8 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 274.1 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 274.1 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 270.7 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 270.7 kB/s eta 0:00:05
     ------------------- -------------------- 1.1/2.2 MB 270.7 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 264.1 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 264.1 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 260.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 260.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 260.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 260.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 260.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 248.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.1/2.2 MB 248.3 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     -------------------- ------------------- 1.2/2.2 MB 244.4 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 227.7 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 227.7 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 227.7 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 227.7 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 227.7 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 221.6 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 221.6 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 218.5 kB/s eta 0:00:05
     --------------------- ------------------ 1.2/2.2 MB 218.5 kB/s eta 0:00:05
     ---------------------- ----------------- 1.2/2.2 MB 218.5 kB/s eta 0:00:05
     ---------------------- ----------------- 1.2/2.2 MB 217.3 kB/s eta 0:00:05
     ---------------------- ----------------- 1.3/2.2 MB 217.9 kB/s eta 0:00:05
     ---------------------- ----------------- 1.3/2.2 MB 217.9 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 217.9 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 217.9 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 217.3 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 216.8 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 216.2 kB/s eta 0:00:05
     ----------------------- ---------------- 1.3/2.2 MB 216.2 kB/s eta 0:00:05
     ------------------------ --------------- 1.4/2.2 MB 216.8 kB/s eta 0:00:05
     ------------------------ --------------- 1.4/2.2 MB 218.5 kB/s eta 0:00:04
     ------------------------ --------------- 1.4/2.2 MB 218.5 kB/s eta 0:00:04
     ------------------------- -------------- 1.4/2.2 MB 220.1 kB/s eta 0:00:04
     ------------------------- -------------- 1.4/2.2 MB 220.6 kB/s eta 0:00:04
     -------------------------- ------------- 1.5/2.2 MB 223.7 kB/s eta 0:00:04
     -------------------------- ------------- 1.5/2.2 MB 224.3 kB/s eta 0:00:04
     -------------------------- ------------- 1.5/2.2 MB 225.8 kB/s eta 0:00:04
     -------------------------- ------------- 1.5/2.2 MB 226.3 kB/s eta 0:00:04
     --------------------------- ------------ 1.5/2.2 MB 229.7 kB/s eta 0:00:03
     --------------------------- ------------ 1.5/2.2 MB 229.2 kB/s eta 0:00:03
     ---------------------------- ----------- 1.6/2.2 MB 230.6 kB/s eta 0:00:03
     ---------------------------- ----------- 1.6/2.2 MB 230.0 kB/s eta 0:00:03
     ---------------------------- ----------- 1.6/2.2 MB 231.4 kB/s eta 0:00:03
     ---------------------------- ----------- 1.6/2.2 MB 231.4 kB/s eta 0:00:03
     ----------------------------- ---------- 1.6/2.2 MB 232.0 kB/s eta 0:00:03
     ------------------------------ --------- 1.7/2.2 MB 232.7 kB/s eta 0:00:03
     ------------------------------ --------- 1.7/2.2 MB 234.0 kB/s eta 0:00:03
     ------------------------------ --------- 1.7/2.2 MB 233.9 kB/s eta 0:00:03
     ------------------------------- -------- 1.7/2.2 MB 234.8 kB/s eta 0:00:03
     ------------------------------- -------- 1.8/2.2 MB 235.9 kB/s eta 0:00:02
     -------------------------------- ------- 1.8/2.2 MB 237.1 kB/s eta 0:00:02
     --------------------------------- ------ 1.8/2.2 MB 239.9 kB/s eta 0:00:02
     --------------------------------- ------ 1.9/2.2 MB 241.4 kB/s eta 0:00:02
     ---------------------------------- ----- 1.9/2.2 MB 243.0 kB/s eta 0:00:02
     ---------------------------------- ----- 1.9/2.2 MB 244.6 kB/s eta 0:00:02
     ---------------------------------- ----- 1.9/2.2 MB 244.8 kB/s eta 0:00:02
     ----------------------------------- ---- 2.0/2.2 MB 246.3 kB/s eta 0:00:02
     ----------------------------------- ---- 2.0/2.2 MB 246.5 kB/s eta 0:00:01
     ------------------------------------ --- 2.0/2.2 MB 248.8 kB/s eta 0:00:01
     ------------------------------------ --- 2.0/2.2 MB 249.5 kB/s eta 0:00:01
     ------------------------------------- -- 2.1/2.2 MB 250.9 kB/s eta 0:00:01
     ------------------------------------- -- 2.1/2.2 MB 251.5 kB/s eta 0:00:01
     -------------------------------------- - 2.1/2.2 MB 253.3 kB/s eta 0:00:01
     -------------------------------------- - 2.2/2.2 MB 255.1 kB/s eta 0:00:01
     ---------------------------------------  2.2/2.2 MB 255.6 kB/s eta 0:00:01
     ---------------------------------------  2.2/2.2 MB 257.3 kB/s eta 0:00:01
     ---------------------------------------- 2.2/2.2 MB 259.1 kB/s eta 0:00:00
Requirement already satisfied: comm>=0.1.3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: jedi>=0.16 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import ipywidgets as widgets
from IPython.display import display, clear_output

In [3]:
age = widgets.IntText(
    description="Age:",
    value=45
)

gender = widgets.Dropdown(
    description="Gender:",
    options=["Male", "Female"],
    value="Male"
)

bmi = widgets.FloatText(
    description="BMI:",
    value=27.5
)

blood_pressure = widgets.IntText(
    description="BP:",
    value=130
)

cholesterol = widgets.IntText(
    description="Cholesterol:",
    value=210
)

glucose = widgets.IntText(
    description="Glucose:",
    value=115
)

heart_rate = widgets.IntText(
    description="Heart Rate:",
    value=78
)

smoking = widgets.Dropdown(
    description="Smoking:",
    options=["Yes", "No"],
    value="No"
)

physical_activity = widgets.Dropdown(
    description="Activity:",
    options=["Low", "Medium", "High"],
    value="Medium"
)

family_history = widgets.Dropdown(
    description="Family History:",
    options=["Yes", "No"],
    value="Yes"
)

In [4]:
predict_button = widgets.Button(
    description="Predict Disease Risk",
    button_style="primary"
)

output = widgets.Output()

In [5]:
def on_predict_clicked(button):

    with output:
        clear_output()

        patient = {
            "Age": age.value,
            "BMI": bmi.value,
            "BloodPressure": blood_pressure.value,
            "Cholesterol": cholesterol.value,
            "Glucose": glucose.value,
            "HeartRate": heart_rate.value,
            "Gender": gender.value,
            "Smoking": smoking.value,
            "PhysicalActivity": physical_activity.value,
            "FamilyHistory": family_history.value
        }

        risk, probability = predict_disease_risk(patient)

        print("=" * 40)
        print("       DISEASE RISK RESULT")
        print("=" * 40)

        print("Risk:", risk)
        print(
            "Probability:",
            round(probability * 100, 2),
            "%"
        )

        print("=" * 40)

In [6]:
predict_button.on_click(on_predict_clicked)

In [7]:
display(
    age,
    gender,
    bmi,
    blood_pressure,
    cholesterol,
    glucose,
    heart_rate,
    smoking,
    physical_activity,
    family_history,
    predict_button,
    output
)

IntText(value=45, description='Age:')

Dropdown(description='Gender:', options=('Male', 'Female'), value='Male')

FloatText(value=27.5, description='BMI:')

IntText(value=130, description='BP:')

IntText(value=210, description='Cholesterol:')

IntText(value=115, description='Glucose:')

IntText(value=78, description='Heart Rate:')

Dropdown(description='Smoking:', index=1, options=('Yes', 'No'), value='No')

Dropdown(description='Activity:', index=1, options=('Low', 'Medium', 'High'), value='Medium')

Dropdown(description='Family History:', options=('Yes', 'No'), value='Yes')

Button(button_style='primary', description='Predict Disease Risk', style=ButtonStyle())

Output()

In [8]:
import ipywidgets as widgets
from IPython.display import display

display(widgets.IntText(
    value=25,
    description="Test Age:"
))

IntText(value=25, description='Test Age:')

In [9]:
!pip install -U ipywidgets

Requirement already satisfied: ipywidgets in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (8.1.9)
Requirement already satisfied: widgetsnbextension~=4.0.16 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (4.0.16)
Requirement already satisfied: ipython>=6.1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (8.39.0)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (3.0.17)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (5.15.1)
Requirement already satisfied: comm>=0.1.3 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: matplotlib-inline in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: stack_data in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: decorator in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.3.1)
Requirement already satisfied: jedi>=0.16 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: pygments>=2.4.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: exceptiongroup in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.3.1)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (4.16.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: wcwidth in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: executing>=1.2.0 in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: pure-eval in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import streamlit

print("Streamlit version:", streamlit.__version__)

Streamlit version: 1.61.0

In [11]:
import streamlit as st

st.set_page_config(
    page_title="Healthcare Disease Risk Prediction",
    page_icon="🏥",
    layout="wide"
)

st.title("🏥 Healthcare Disease Risk Prediction")
st.write(
    "Machine Learning based disease risk prediction system"
)

st.success("Application started successfully!")

2026-09-15 09:28:35.287 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:35.291 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.693
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-09-15 09:28:36.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.702 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-15 09:28:36.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [12]:
import joblib

saved_model = joblib.load("../models/healthcare_disease_risk_model.pkl")

print("Model type:")
print(type(saved_model))

print("\nModel parameters:")
print(saved_model.get_params())

Model type:
<class 'xgboost.sklearn.XGBClassifier'>

Model parameters:
{'objective': 'binary:logistic', 'base_score': None, 'booster': None, 'callbacks': None, 'colsample_bylevel': None, 'colsample_bynode': None, 'colsample_bytree': 0.7, 'device': None, 'early_stopping_rounds': None, 'enable_categorical': False, 'eval_metric': 'logloss', 'feature_types': None, 'feature_weights': None, 'gamma': None, 'grow_policy': None, 'importance_type': None, 'interaction_constraints': None, 'learning_rate': 0.2, 'max_bin': None, 'max_cat_threshold': None, 'max_cat_to_onehot': None, 'max_delta_step': None, 'max_depth': 5, 'max_leaves': None, 'min_child_weight': 5, 'missing': nan, 'monotone_constraints': None, 'multi_strategy': None, 'n_estimators': 500, 'n_jobs': None, 'num_parallel_tree': None, 'random_state': 42, 'reg_alpha': None, 'reg_lambda': None, 'sampling_method': None, 'scale_pos_weight': None, 'subsample': 0.7, 'tree_method': None, 'validate_parameters': None, 'verbosity': None}